### ISSUE TITLE
Devemos traduzir "workspace"?

### ISSUE THREAD

**Issue by dcbmariano** [rafalab/dslivro#17]
@benilton @samarafk @tatibenaglia

Na tradução automática, a palavra "workspace" foi traduzida para "área de trabalho" ou "espaço de trabalho". Devemos traduzir essa palavra ou mantemos a versão original? 

Atualmente, mantive a tradução original e coloquei a palavra "workspace" entre parênteses.

Acredito que devemos criar uma espécie de dicionário ou ontologia que padronize como certas coisas devem ser traduzidas. Por exemplo, se decidirmos traduzir "workspace" para "área de trabalho", devemos tomar cuidado para sempre manter essa tradução e não usar por exemplo "espaço de trabalho".

**Comment by samarafk** [comment]
"área de trabalho" acho que fica bom

**Comment by dcbmariano** [comment]
criei uma página na wiki com um dicionário para a padronização de traduções
